name: CI/CD Quarkus Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout do código
      uses: actions/checkout@v3
    
    - name: Configurar JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Dar permissão de execução ao mvnw
      run: chmod +x mvnw
    
    - name: Compilar e empacotar aplicação Quarkus
      run: ./mvnw package -DskipTests
    
    - name: Obter hash do commit
      id: vars
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build da imagem docker
      run: |
        docker build -t quarkus-app:${{ env.COMMIT_HASH }} .

    - name: Deploy em ambiente de desenvolvimento
      run: |
        echo "Simulação de deploy do ambiente DEV"

    - name: Deploy em ambiente de produção
      if: github.ref == 'refs/heads/main'
      run: |
        echo  "Simulação de deploy do ambiente PROD"
